// Copyright (c) 2024-2026 Pierre G. Boutquin. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License").
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
namespace Boutquin.Storage.SourceGenerator;

internal static class CodeGenerator
{
    private const string GeneratorName = "Boutquin.Storage.SourceGenerator";
    private const string GeneratorVersion = "1.0.0";

    // BinaryWriter/BinaryReader method names for each primitive kind.
    private static readonly Dictionary<PrimitiveKind, (string Write, string Read)> s_primitiveMethods
        = new()
        {
            [PrimitiveKind.Int] = ("Write", "ReadInt32"),
            [PrimitiveKind.Long] = ("Write", "ReadInt64"),
            [PrimitiveKind.String] = ("Write", "ReadString"),
            [PrimitiveKind.Float] = ("Write", "ReadSingle"),
            [PrimitiveKind.Double] = ("Write", "ReadDouble"),
            [PrimitiveKind.Bool] = ("Write", "ReadBoolean"),
            [PrimitiveKind.Byte] = ("Write", "ReadByte"),
            [PrimitiveKind.Char] = ("Write", "ReadChar"),
        };

    public static string Generate(TypeToGenerate type, StorageDefaultsConfig defaults)
    {
        var sb = new StringBuilder();

        AppendFileHeader(sb);

        // Namespace (file-scoped, omit if global)
        if (type.Namespace is not null)
        {
            sb.AppendLine($"namespace {type.Namespace};");
            sb.AppendLine();
        }

        // Open parent type wrappers (for nested types), outermost first
        int parentDepth = 0;
        foreach (var parent in type.ParentTypes)
        {
            string indent = new string(' ', parentDepth * 4);
            AppendParentOpen(sb, parent, indent);
            parentDepth++;
        }

        // Main type declaration
        string typeIndent = new string(' ', parentDepth * 4);
        AppendTypeDeclaration(sb, type, typeIndent);

        // Open brace
        sb.AppendLine($"{typeIndent}{{");

        // Serialize
        if (!type.SkipSerializable)
        {
            AppendSerialize(sb, type, typeIndent + "    ");
            sb.AppendLine();
            AppendDeserialize(sb, type, typeIndent + "    ");
        }

        // CompareTo (Key only)
        if (type.IsKey && !type.SkipComparable)
        {
            sb.AppendLine();
            AppendCompareTo(sb, type, typeIndent + "    ");
        }

        // Equals / GetHashCode / operators (Key only, skip for record structs which synthesize these)
        if (type.IsKey && !type.SkipEquatable && !type.IsRecordStruct)
        {
            sb.AppendLine();
            AppendEquality(sb, type, typeIndent + "    ");
        }

        // Comparison operators (Key only, controlled by defaults)
        if (type.IsKey && !type.SkipComparable && defaults.GenerateComparisonOperators)
        {
            sb.AppendLine();
            AppendComparisonOperators(sb, type, typeIndent + "    ");
        }

        // Close type
        sb.AppendLine($"{typeIndent}}}");

        // Close parent type wrappers (innermost first)
        for (int i = parentDepth - 1; i >= 0; i--)
        {
            string indent = new string(' ', i * 4);
            sb.AppendLine($"{indent}}}");
        }

        return sb.ToString();
    }

    private static void AppendFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// Copyright © 2024-present Pierre G. Boutquin. All rights reserved.");
        sb.AppendLine("// Licensed under the Apache License, Version 2.0.");
        sb.AppendLine("// See LICENSE file in the project root for full license information.");
        sb.AppendLine("//");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// This code was generated by {GeneratorName}.");
        sb.AppendLine("// Do not edit this file manually.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable 1591  // Missing XML comment");
        sb.AppendLine("#pragma warning disable CA1036 // Override methods on comparable types");
        sb.AppendLine("#pragma warning disable IDE0073 // File header (generated file has its own header)");
        sb.AppendLine();
    }

    private static void AppendParentOpen(StringBuilder sb, ParentTypeInfo parent, string indent)
    {
        string generic = parent.GenericParameters ?? "";
        string constraints = parent.Constraints is not null ? $" {parent.Constraints}" : "";
        sb.AppendLine($"{indent}{parent.Modifiers} {parent.Kind} {parent.Name}{generic}{constraints}");
        sb.AppendLine($"{indent}{{");
    }

    private static void AppendTypeDeclaration(StringBuilder sb, TypeToGenerate type, string indent)
    {
        sb.AppendLine($"{indent}[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{GeneratorName}\", \"{GeneratorVersion}\")]");
        sb.AppendLine($"{indent}[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");

        var interfaces = new List<string>();
        if (!type.SkipSerializable)
        {
            interfaces.Add($"global::Boutquin.Storage.Domain.Interfaces.ISerializable<{type.Name}>");
        }

        if (type.IsKey && !type.SkipComparable)
        {
            interfaces.Add($"global::System.IComparable<{type.Name}>");
        }
        // Record structs already synthesize IEquatable<T> — don't re-declare it
        if (type.IsKey && !type.SkipEquatable && !type.IsRecordStruct)
        {
            interfaces.Add($"global::System.IEquatable<{type.Name}>");
        }

        string baseList = interfaces.Count > 0 ? " :\n" + indent + "    " + string.Join(",\n" + indent + "    ", interfaces) : "";
        sb.AppendLine($"{indent}{type.Accessibility} partial record struct {type.Name}{baseList}");
    }

    private static void AppendSerialize(StringBuilder sb, TypeToGenerate type, string indent)
    {
        sb.AppendLine($"{indent}public void Serialize(global::System.IO.Stream stream)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    using var writer = new global::System.IO.BinaryWriter(stream, global::System.Text.Encoding.UTF8, leaveOpen: true);");

        foreach (var prop in type.Properties)
        {
            if (prop.Kind == TypeKind.Unsupported)
            {
                continue;
            }

            AppendSerializeProperty(sb, prop, indent + "    ");
        }

        sb.AppendLine($"{indent}}}");
    }

    private static void AppendSerializeProperty(StringBuilder sb, PropertyInfo prop, string indent)
    {
        switch (prop.Kind)
        {
            case TypeKind.Primitive:
                if (prop.Primitive == PrimitiveKind.String)
                {
                    // Null guard for string — BinaryWriter.Write(string) throws ArgumentNullException on null
                    sb.AppendLine($"{indent}writer.Write({prop.Name} ?? throw new global::System.InvalidOperationException(\"Property '{prop.Name}' cannot be null during serialization.\"));");
                }
                else
                {
                    sb.AppendLine($"{indent}writer.Write({prop.Name});");
                }
                break;

            case TypeKind.AnnotatedType:
                sb.AppendLine($"{indent}{prop.Name}.Serialize(stream);");
                break;

            case TypeKind.PrimitiveCollection:
                sb.AppendLine($"{indent}var {prop.Name}List = new global::System.Collections.Generic.List<{prop.AnnotatedTypeName}>({prop.Name});");
                sb.AppendLine($"{indent}writer.Write({prop.Name}List.Count);");
                sb.AppendLine($"{indent}foreach (var item in {prop.Name}List)");
                sb.AppendLine($"{indent}{{");
                if (prop.Primitive == PrimitiveKind.String)
                {
                    sb.AppendLine($"{indent}    writer.Write(item ?? throw new global::System.InvalidOperationException(\"Collection element in '{prop.Name}' cannot be null during serialization.\"));");
                }
                else
                {
                    sb.AppendLine($"{indent}    writer.Write(item);");
                }

                sb.AppendLine($"{indent}}}");
                break;

            case TypeKind.AnnotatedCollection:
                sb.AppendLine($"{indent}var {prop.Name}List = new global::System.Collections.Generic.List<{prop.AnnotatedTypeName}>({prop.Name});");
                sb.AppendLine($"{indent}writer.Write({prop.Name}List.Count);");
                sb.AppendLine($"{indent}foreach (var item in {prop.Name}List)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    item.Serialize(stream);");
                sb.AppendLine($"{indent}}}");
                break;
        }
    }

    private static void AppendDeserialize(StringBuilder sb, TypeToGenerate type, string indent)
    {
        sb.AppendLine($"{indent}public static {type.Name} Deserialize(global::System.IO.Stream stream)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    using var reader = new global::System.IO.BinaryReader(stream, global::System.Text.Encoding.UTF8, leaveOpen: true);");

        var ctorArgs = new List<string>();
        foreach (var prop in type.Properties)
        {
            if (prop.Kind == TypeKind.Unsupported)
            {
                ctorArgs.Add("default");
                continue;
            }

            AppendDeserializeProperty(sb, prop, indent + "    ");
            ctorArgs.Add($"_{prop.Name}");
        }

        sb.AppendLine($"{indent}    return new {type.Name}({string.Join(", ", ctorArgs)});");
        sb.AppendLine($"{indent}}}");
    }

    private static void AppendDeserializeProperty(StringBuilder sb, PropertyInfo prop, string indent)
    {
        switch (prop.Kind)
        {
            case TypeKind.Primitive:
                string readMethod = s_primitiveMethods[prop.Primitive!.Value].Read;
                sb.AppendLine($"{indent}var _{prop.Name} = reader.{readMethod}();");
                break;

            case TypeKind.AnnotatedType:
                sb.AppendLine($"{indent}var _{prop.Name} = {prop.AnnotatedTypeName}.Deserialize(stream);");
                break;

            case TypeKind.PrimitiveCollection:
                string elemRead = s_primitiveMethods[prop.Primitive!.Value].Read;
                sb.AppendLine($"{indent}var _{prop.Name}Count = reader.ReadInt32();");
                sb.AppendLine($"{indent}var _{prop.Name} = new global::System.Collections.Generic.List<{prop.AnnotatedTypeName}>();");
                sb.AppendLine($"{indent}for (int i = 0; i < _{prop.Name}Count; i++)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    _{prop.Name}.Add(reader.{elemRead}());");
                sb.AppendLine($"{indent}}}");
                break;

            case TypeKind.AnnotatedCollection:
                sb.AppendLine($"{indent}var _{prop.Name}Count = reader.ReadInt32();");
                sb.AppendLine($"{indent}var _{prop.Name} = new global::System.Collections.Generic.List<{prop.AnnotatedTypeName}>();");
                sb.AppendLine($"{indent}for (int i = 0; i < _{prop.Name}Count; i++)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    _{prop.Name}.Add({prop.AnnotatedTypeName}.Deserialize(stream));");
                sb.AppendLine($"{indent}}}");
                break;
        }
    }

    private static void AppendCompareTo(StringBuilder sb, TypeToGenerate type, string indent)
    {
        sb.AppendLine($"{indent}public int CompareTo({type.Name} other)");
        sb.AppendLine($"{indent}{{");

        var compareableProps = type.Properties
            .Where(p => p.Kind != TypeKind.Unsupported &&
                        p.Kind != TypeKind.PrimitiveCollection &&
                        p.Kind != TypeKind.AnnotatedCollection)
            .ToList();

        if (compareableProps.Count == 0)
        {
            sb.AppendLine($"{indent}    return 0;");
        }
        else if (compareableProps.Count == 1)
        {
            sb.AppendLine($"{indent}    return global::Boutquin.Storage.Domain.Helpers.ComparisonHelper.SafeCompareTo(this.{compareableProps[0].Name}, other.{compareableProps[0].Name});");
        }
        else
        {
            // Multi-property: chained lexicographic
            for (int i = 0; i < compareableProps.Count - 1; i++)
            {
                string varName = $"cmp{i}";
                sb.AppendLine($"{indent}    var {varName} = global::Boutquin.Storage.Domain.Helpers.ComparisonHelper.SafeCompareTo(this.{compareableProps[i].Name}, other.{compareableProps[i].Name});");
                sb.AppendLine($"{indent}    if ({varName} != 0) return {varName};");
            }
            var last = compareableProps[compareableProps.Count - 1];
            sb.AppendLine($"{indent}    return global::Boutquin.Storage.Domain.Helpers.ComparisonHelper.SafeCompareTo(this.{last.Name}, other.{last.Name});");
        }

        sb.AppendLine($"{indent}}}");
    }

    private static void AppendEquality(StringBuilder sb, TypeToGenerate type, string indent)
    {
        var allProps = type.Properties.Where(p => p.Kind != TypeKind.Unsupported).ToList();

        // Equals(T)
        sb.AppendLine($"{indent}public bool Equals({type.Name} other)");
        sb.AppendLine($"{indent}{{");
        if (allProps.Count == 0)
        {
            sb.AppendLine($"{indent}    return true;");
        }
        else
        {
            var conditions = allProps.Select(p =>
                $"global::System.Collections.Generic.EqualityComparer<{p.TypeName}>.Default.Equals(this.{p.Name}, other.{p.Name})");
            sb.AppendLine($"{indent}    return {string.Join("\n{indent}        && ", conditions.ToArray())};");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        // Equals(object)
        sb.AppendLine($"{indent}public override bool Equals(object? obj) => obj is {type.Name} other && Equals(other);");
        sb.AppendLine();

        // GetHashCode
        sb.AppendLine($"{indent}public override int GetHashCode()");
        sb.AppendLine($"{indent}{{");
        if (allProps.Count == 0)
        {
            sb.AppendLine($"{indent}    return 0;");
        }
        else if (allProps.Count == 1)
        {
            sb.AppendLine($"{indent}    return global::System.Collections.Generic.EqualityComparer<{allProps[0].TypeName}>.Default.GetHashCode({allProps[0].Name});");
        }
        else
        {
            var args = string.Join(", ", allProps.Select(p => p.Name));
            sb.AppendLine($"{indent}    return global::System.HashCode.Combine({args});");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        // == and !=
        sb.AppendLine($"{indent}public static bool operator ==({type.Name} left, {type.Name} right) => left.Equals(right);");
        sb.AppendLine($"{indent}public static bool operator !=({type.Name} left, {type.Name} right) => !left.Equals(right);");
    }

    private static void AppendComparisonOperators(StringBuilder sb, TypeToGenerate type, string indent)
    {
        sb.AppendLine($"{indent}public static bool operator <({type.Name} left, {type.Name} right) => left.CompareTo(right) < 0;");
        sb.AppendLine($"{indent}public static bool operator >({type.Name} left, {type.Name} right) => left.CompareTo(right) > 0;");
        sb.AppendLine($"{indent}public static bool operator <=({type.Name} left, {type.Name} right) => left.CompareTo(right) <= 0;");
        sb.AppendLine($"{indent}public static bool operator >=({type.Name} left, {type.Name} right) => left.CompareTo(right) >= 0;");
    }
}
