// <auto-generated>
// WARNING: This code was generated by a source generator.
// Any changes to this file may be overwritten.
// </auto-generated>
//
// Copyright (c) 2024 Pierre G. Boutquin. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
namespace Boutquin.Storage.Samples;

using System.IO;

public partial record struct Attraction : ISerializable<Attraction>
{
    public void Serialize(BinaryWriter writer)
    {
        writer.Write(Name);
    }

    public static Attraction Deserialize(BinaryReader reader)
    {
        return new Attraction(reader.ReadString());
    }
}
